### ISSUE TITLE
ArgoCDのChapterの追加・修正

### ISSUE THREAD

**Issue by TatsukiMinami** [cloudnativedaysjp/cnd-handson#261]
* [ ] コード化を行う（WebUIからだけではなく、argocd CLIとApplicationリソースを使った形にする）
    * 両方とも残した形で、タブで切り替えられるようにする
![image](https://github.com/cloudnativedaysjp/cnd-handson/assets/8783194/33b91d61-b4d7-4547-b5e2-b31d68d33118)

**Comment by akiran123** [comment]
docsifyで作ってみたのですが、、、ページのスクロールができない・・・
もう少し考えてみます。何かいい案とかありますでしょうか・・・
