### ISSUE TITLE
[Prometheus] 利用のイメージがあった方が良いかも

### ISSUE THREAD

**Issue by ystkfujii** [cloudnativedaysjp/cnd-handson#363]
「Promethesuについて」でもう少し、Prometheusの説明（なにができるのか？）を入れた方がよいかなと思いました。  

たとえば、よくある利用方法としては下記図のようになって、メモリが閾値超えたらSlackにアラートが飛ばせまーす。とか

![image](https://github.com/user-attachments/assets/1b8c8cd0-67d0-4f15-936b-82e15f9aa938)

**Comment by akiran123** [comment]
https://github.com/cloudnativedaysjp/cnd-handson/pull/377
で対応済み
