### ISSUE TITLE
[Prometheus] PodMonitorとServiceMonitorに関する説明について

### ISSUE THREAD

**Issue by ystkfujii** [cloudnativedaysjp/cnd-handson#364]
> ServiceMonitorオブジェクトは、サービスのエンドポイントからメトリクスを収集することができます。

と書いてますが、これだとServiceリソースにアクセスしてメトリクスを収集していると誤解されるかも？

書き方はいろいろあると思いますが、たとえば、公式のドキュメントベースの説明にした方が良いかも。

- https://prometheus-operator.dev/docs/getting-started/design/#servicemonitor

そうすると今度は、PodMonitorとServiceMonitorでできることが同じに見え、どう使い分けたら良いのか分からなくなると思うので、下記のコメントを引用してフォローもしておくとより良いかも。

 - https://github.com/prometheus-operator/prometheus-operator/issues/3119#issuecomment-610445145

**Comment by Himalayan-wildcat** [comment]
Pod monitor VS Service monitorは過去に質問を受けた記憶があるので、使い分け、ユースケースなど追記するのは 👍 です。

**Comment by akiran123** [comment]
https://github.com/cloudnativedaysjp/cnd-handson/pull/378

**Comment by akiran123** [comment]
https://github.com/cloudnativedaysjp/cnd-handson/pull/378
こちらで対応済み
