### ISSUE TITLE
[Grafana]サンプルアラートの説明について

### ISSUE THREAD

**Issue by ystkfujii** [cloudnativedaysjp/cnd-handson#366]
- １点目）説明がBuilderモードでの説明となっていますが、デフォルトがCodeモードになっていたので少し混乱するかも
  -  画面のスクショ等の追加の説明があった方がよいかもです
- ２点目）ブロック（？）ごとに説明を分けた方がよいかも？
  - Alert ruleの作成は下記のブロックごとに設定を行う
    - 1. Enter alert rule name
    - 2. Define query and alert condition
    - 3. Set evaluation behavior
    - 4. Configure labels and notifications
    - 5. Add annotations
  - 本文の説明として、上記のブロックについて言及しない説明になっており、どのブロックの設定になるのか少し混乱しました

**Comment by yuta1979** [comment]
こちらのプルリクエストで対応ずみ
https://github.com/cloudnativedaysjp/cnd-handson/pull/393
