### ISSUE TITLE
[Grafana]使用している画像について

### ISSUE THREAD

**Issue by ystkfujii** [cloudnativedaysjp/cnd-handson#367]
若干画像が違う部分があるので、可能なのであれば全体的に差し替えた方がよいかも？  
ただ、画面はよく変わるし、今の画像でもハンズオン自体はできると思うので、タスク状況によってはやらない選択肢もありだと思います。

以下気づいた点

- 謎の白いスペースがある
  - https://github.com/cloudnativedaysjp/cnd-handson/blob/cndw2024/chapter_grafana/image/dashboards.png
- adminの画面ではない？画像がちらほら
  - adminでログインする想定だと思うので、画面も合わせた方が良いかも？
  - これとか：https://github.com/cloudnativedaysjp/cnd-handson/blob/cndw2024/chapter_grafana/image/import-dashboard.png
- Grafanaのversionアップによる変更？
  - タブに変わってる
  - https://github.com/cloudnativedaysjp/cnd-handson/blob/cndw2024/chapter_grafana/image/notifications.png

**Comment by yuta1979** [comment]
こちらのプルリクエストで対応済み
https://github.com/cloudnativedaysjp/cnd-handson/pull/393
