### ISSUE TITLE
[ArgoCD] ArgoCDの手順において、CLIの手順の途中で突然WebUIからの操作が前置きなしに書かれているため修正を検討

### ISSUE THREAD

**Issue by nouphet** [cloudnativedaysjp/cnd-handson#385]
https://github.com/cloudnativedaysjp/cnd-handson/blob/b5b06fa46a971abd4b6071e442ddbb8231591632/chapter_argocd/README_cli.md?plain=1#L442

Chapter ArgoCDなんですが、CLIの手順の途中で突然WebUIからの操作が前置きなしに書かれています。
(戸惑いましたが、ChatGPTに質問した結果、GENERALのセクションの内容に従ってWebUIから設定入れていけば良いのだとわかりました)

どう直せばよいのかわからないのですが、コマンドで実行する流れでわかるように書き直したほうが良さそうに思いました。

いかかでしょうか？

**Comment by mongamae-nioh** [comment]
https://github.com/cloudnativedaysjp/cnd-handson/pull/392 で解決済み
