### ISSUE TITLE
[Argo Rollouts] Web metrics (Blue/Green Deploy) でAnalysisrunが失敗したあと、どのように成功させればよいのかが不明

### ISSUE THREAD

**Issue by nouphet** [cloudnativedaysjp/cnd-handson#389]
https://github.com/cloudnativedaysjp/cnd-handson/blob/b5b06fa46a971abd4b6071e442ddbb8231591632/chapter_argo-rollouts/README.md?plain=1#L363

Web metrics (Blue/Green Deploy) のシナリオでAnalysisrunが失敗しました。
本来は成功するはずがバージョンアップの影響で失敗したのか、いったん失敗させたあと成功させる想定なのに操作の記述が不足しているのかがわからないのですが、いったんIssueにて報告しておきます。
![Monosnap web - Application Details Tree - Argo CD 2024-10-20 00-30-25](https://github.com/user-attachments/assets/cedb2520-de76-4367-bedb-e277c5388434)

**Comment by akiran123** [comment]
おや・・・僕の環境だと・・・webはきちんと動作していそうですね。
なんでだ・・・。
![スクリーンショット 2024-10-21 14 40 05](https://github.com/user-attachments/assets/c3575d66-f8f6-42b9-a0b4-ef461781d40b)

**Comment by Himalayan-wildcat** [comment]
@nouphet 
こちら解決済みですか？
