### ISSUE TITLE
[OpenTelemetry] README 説明とコードに違いがあると思われますので、確認をお願いします。

### ISSUE THREAD

**Issue by nouphet** [cloudnativedaysjp/cnd-handson#400]
https://github.com/cloudnativedaysjp/cnd-handson/blob/417391d1269b1f994ea6cc59550edc156d858e66/chapter_opentelemetry/README.md?plain=1#L465C1-L474C21

465行目なんですが、説明では DaemonSet として起動すると書いていますが、コードでは deployment になっているようです。

### 説明文

`.spec.mode`にはdaemonsetを指定し、DaemonSetとして起動します。

### コード

```
spec:
  mode: "deployment"
```

## 修正案

1. DaemonSet とするべきであればコードを修正する
2. Deployment で問題ないのであれば説明文を修正する

(もし私の勘違いであればそのままCloseしてください)

**Comment by Himalayan-wildcat** [comment]
@nouphet 

Deploymentで良いはずですね。
Instrumentationリソースで指定されたエンドポイントに(otel collector)にトレース情報を送るので。

**Comment by TatsukiMinami** [comment]
これコード上はdaemonsetなんですよね

**Comment by nouphet** [comment]
149行目はその通りで合っているんですが、465行目が違っているようなんですよね。

**Comment by nouphet** [comment]
Meeting で Deployment が正しいことが確認されました。
https://github.com/cloudnativedaysjp/cnd-handson/issues/400#issuecomment-2433771516

**Comment by nouphet** [comment]
@Himalayan-wildcat 

これ、行ごと削除でも問題ないですかね？

```
今回はトレースデータの取得先ホスト上のメトリクスを取得するエージェントとして動作させる想定なため、`.spec.mode`にはdaemonsetを指定し、DaemonSetとして起動します。
```

**Comment by Himalayan-wildcat** [comment]
@nouphet 

> これ、行ごと削除でも問題ないですかね？

私は👍+1です。

**Comment by Himalayan-wildcat** [comment]
@nouphet @TatsukiMinami 
他のOtel chapterの修正事項と併せてこちらのIssue内容も対応予定のため、本件クローズします。
