### ISSUE TITLE
Argo CD(UI版)のKustomizeの箇所でイメージが表示されていない

### ISSUE THREAD

**Issue by Himalayan-wildcat** [cloudnativedaysjp/cnd-handson#417]
Argo CD(UI版)で[Kustomizeを利用](https://github.com/cloudnativedaysjp/cnd-handson/blob/cndw2024/chapter_argocd/README_webui.md#%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83)する箇所で、イメージがレンダリングされていない。

**Comment by Himalayan-wildcat** [comment]
@hayama17 @akiran123 @mongamae-nioh 

お手隙の際にご確認いただけますか？

**Comment by akiran123** [comment]
追加しました。
Commitしました。
もし良かったら確認いただいて、問題なかったらクローズいただけると！

**Comment by Himalayan-wildcat** [comment]
@akiran123 
すみません、該当のコミットはどちらになりますか？

**Comment by akiran123** [comment]
ですです〜！

**Comment by Himalayan-wildcat** [comment]
https://github.com/cloudnativedaysjp/cnd-handson/commit/5aa1715db2ae147e1e57d2692ecd5f4db5b172a6 で対応済み。
本件クローズ。
