### ISSUE TITLE
`chapter_argo-rollouts`のクリーンアップでArgo CDリソースが削除できない、またはエラーが出る

### ISSUE THREAD

**Issue by Himalayan-wildcat** [cloudnativedaysjp/cnd-handson#418]
Argo CDを[削除](https://github.com/cloudnativedaysjp/cnd-handson/tree/cndw2024/chapter_argo-rollouts#argo-cd%E3%82%92%E5%89%8A%E9%99%A4)するところで、

- argocd serverが内部的にargo rolloutsのUI extensionをインストールするので、`kubectl delete -n argo-cd -f https://raw.githubusercontent.com/argoproj-labs/rollout-extension/v0.2.1/manifests/install.yaml` は不要な感じです。`ArgoCDExtension` CRの削除はチャプターを進める段階でCRDをインストールしていないので、エラーになる気が。
- `argo-cd` k8s namespaceの削除前にingressを削除してあげないと、同nsは削除不可な気がします。

**Comment by Himalayan-wildcat** [comment]
@hayama17 @akiran123 @mongamae-nioh 

お手隙の際にご確認お願いします〜。

**Comment by akiran123** [comment]
@Himalayan-wildcat 
```
error: resource mapping not found for name: "argo-rollouts" namespace: "" from "https://raw.githubusercontent.com/argoproj-labs/rollout-extension/v0.2.1/manifests/install.yaml": no matches for kind "ArgoCDExtension" in version "argoproj.io/v1alpha1"
ensure CRDs are installed first
```
`kubectl delete -n argo-cd -f https://raw.githubusercontent.com/argoproj-labs/rollout-extension/v0.2.1/manifests/install.yaml`
これ不要ですね。削除しておきます！

あと、argo-cdのnamespace削除は、問題なくできたので、このままで問題ないかと思います。

こちらにコメントもらえれば、修正してクローズしておきます！

**Comment by akiran123** [comment]
@Himalayan-wildcat 
テストしてみたところ、ingressリソースを消さずに、ns削除してみたところ、削除できました！

**Comment by Himalayan-wildcat** [comment]
@akiran123 

なるほど、metadataに`finalizers`フィールドないから削除できている感じですね。
であれば、`helmfile destroy -f  ../chapter_argocd/helm/helmfile.yaml`をせずとも、`kubectl delete namespace argo-cd`で全部Argo CDリソース削除できちゃうと思うので、

```sh
helmfile destroy -f  ../chapter_argocd/helm/helmfile.yaml
kubectl delete namespace argo-cd
```
この流れでArgo CDリソースを削除するのであれば、namespaceを削除する前に、ingressを削除してあげた方が良い気がします。（それか、`argo-cd` namespaceを削除すれば、全部削除可能ですね。）

**Comment by akiran123** [comment]
`kubectl delete namespace argo-cd`
だけでいきましょうか〜。そのほうが手間的には簡単だと思うので〜

**Comment by Himalayan-wildcat** [comment]
https://github.com/cloudnativedaysjp/cnd-handson/commit/5d6fa4e6e1f3981ae7b42a4d25207b4dd97ab69d 対応済み。
本件クローズ。
